name: Build external-secrets.io offline docs
on:
  push:
    branches: [main]
    paths:
      - 'external-secrets-io/**'
      - '.github/workflows/build-external-secrets-io.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout official external-secrets repository
        uses: actions/checkout@v4
        with:
          repository: external-secrets/external-secrets
          path: external-secrets-io/external-secrets-src
          fetch-depth: 1

      - name: Prepare tags and environment
        id: prep
        run: |
          cd external-secrets-io/external-secrets-src
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: ./.github/actions/build-and-push-offline-docs
        with:
          image: external-secrets-offline-docs
          context: ./external-secrets-io
          version-tag: ${{ env.COMMIT_SHA }}
