name: Build docs.percona.com offline docs

on:
  push:
    branches: [main]
    paths:
      - 'docs-percona-com/**'
      - '.github/workflows/build-docs-percona-com.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout official Percona Server for MySQL docs repository
        uses: actions/checkout@v4
        with:
          repository: percona/psmysql-docs
          ref: '8.4'
          path: docs-percona-com/percona-src
          fetch-depth: 1

      - name: Prepare tags and environment
        id: prep
        run: |
          cd docs-percona-com/percona-src
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: ./.github/actions/build-and-push-offline-docs
        with:
          image: percona-offline-docs
          context: ./docs-percona-com
          version-tag: ${{ env.COMMIT_SHA }}
