name: Build Grafana offline docs
on:
  push:
    branches: [main]
    paths:
      - 'grafana-com-grafana/**'
      - '.github/workflows/build-grafana-com-grafana.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout official Grafana repository (shallow, docs subtree only)
        uses: actions/checkout@v4
        with:
          repository: grafana/grafana
          path: grafana-com-grafana/grafana-src
          fetch-depth: 1
          sparse-checkout: |
            docs

      - name: Prepare tags and environment
        id: prep
        run: |
          cd grafana-com-grafana/grafana-src
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: ./.github/actions/build-and-push-offline-docs
        with:
          image: grafana-offline-docs
          context: ./grafana-com-grafana
          version-tag: ${{ env.COMMIT_SHA }}
