name: Build Grafana Loki offline docs
on:
  push:
    branches: [main]
    paths:
      - 'grafana-com-loki/**'
      - '.github/workflows/build-grafana-com-loki.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      - name: Checkout official Loki repository
        uses: actions/checkout@v4
        with:
          repository: grafana/loki
          path: grafana-com-loki/loki-src
          fetch-depth: 1
      - name: Prepare tags and environment
        id: prep
        run: |
          cd grafana-com-loki/loki-src
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build and push
        uses: ./.github/actions/build-and-push-offline-docs
        with:
          image: loki-offline-docs
          context: ./grafana-com-loki
          version-tag: ${{ env.COMMIT_SHA }}
