name: Build strimzi.io offline docs

on:
  push:
    branches: [main]
    paths:
      - 'strimzi-io/**'
      - '.github/workflows/build-strimzi-io.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout official Strimzi website repository
        uses: actions/checkout@v4
        with:
          repository: strimzi/strimzi.github.io
          path: strimzi-io/strimzi-src
          fetch-depth: 1

      - name: Prepare tags and environment
        id: prep
        run: |
          cd strimzi-io/strimzi-src
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: ./.github/actions/build-and-push-offline-docs
        with:
          image: strimzi-offline-docs
          context: ./strimzi-io
          version-tag: ${{ env.COMMIT_SHA }}
