name: Build Offline Docs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      site_to_build:
        description: 'Select which documentation site to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - argo-cd-readthedocs-io
          - cert-manager-io
          - docs-ceph-com
          - fluxcd-io
          - kubernetes-io
          - tekton-dev

permissions:
  contents: read
  packages: write

jobs:
  build-kubernetes-io:
    if: >
      github.event_name == 'schedule' || 
      github.event.inputs.site_to_build == 'all' || 
      github.event.inputs.site_to_build == 'kubernetes-io'
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout official Kubernetes website repository
        uses: actions/checkout@v4
        with:
          repository: kubernetes/website
          path: kubernetes-io/k8s-website
          submodules: true
          fetch-depth: 1

      - name: Prepare tags and environment
        id: prep
        run: |
          cd kubernetes-io/k8s-website
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LC=${OWNER_LC}" >> $GITHUB_ENV

          DETECTED_VERSIONS=$(git ls-remote --heads origin | grep -o 'refs/heads/release-1\.[0-9]*' | sed 's|refs/heads/||' | sort -uV | tail -n 5 | tr '\n' ' ' | xargs)
          
          echo "Detected versions to build: $DETECTED_VERSIONS"
          echo "OLD_VERSIONS=$DETECTED_VERSIONS" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Kubernetes image
        uses: docker/build-push-action@v5
        with:
          context: ./kubernetes-io
          file: ./kubernetes-io/Dockerfile
          push: true
          # Pass the dynamically detected versions into the Dockerfile
          build-args: |
            OLD_VERSIONS=${{ env.OLD_VERSIONS }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/k8s-offline-docs:latest
            ghcr.io/${{ env.OWNER_LC }}/k8s-offline-docs:${{ env.COMMIT_SHA }}
          cache-from: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/k8s-offline-docs:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/k8s-offline-docs:buildcache,mode=max

  build-tekton-dev:
    if: >
      github.event_name == 'schedule' || 
      github.event.inputs.site_to_build == 'all' || 
      github.event.inputs.site_to_build == 'tekton-dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout official Tekton website repository
        uses: actions/checkout@v4
        with:
          repository: tektoncd/website
          path: tekton-dev/tekton-website
          submodules: true
          fetch-depth: 1

      - name: Prepare tags and environment
        id: prep
        run: |
          cd tekton-dev/tekton-website
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LC=${OWNER_LC}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Tekton image
        uses: docker/build-push-action@v5
        with:
          context: ./tekton-dev
          file: ./tekton-dev/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/tekton-offline-docs:latest
            ghcr.io/${{ env.OWNER_LC }}/tekton-offline-docs:${{ env.COMMIT_SHA }}
          cache-from: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/tekton-offline-docs:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/tekton-offline-docs:buildcache,mode=max

  build-cert-manager-docs:
    if: >
      github.event_name == 'schedule' || 
      github.event.inputs.site_to_build == 'all' || 
      github.event.inputs.site_to_build == 'cert-manager-io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout official cert-manager website repository
        uses: actions/checkout@v4
        with:
          repository: cert-manager/website
          path: cert-manager-io/cert-manager-website # Updated path
          fetch-depth: 1

      - name: Prepare tags and environment
        id: prep
        run: |
          cd cert-manager-io/cert-manager-website # Updated path
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LC=${OWNER_LC}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push cert-manager image
        uses: docker/build-push-action@v5
        with:
          context: ./cert-manager-io # Updated context
          file: ./cert-manager-io/Dockerfile # Updated path
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/cert-manager-offline-docs:latest
            ghcr.io/${{ env.OWNER_LC }}/cert-manager-offline-docs:${{ env.COMMIT_SHA }}
          cache-from: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/cert-manager-offline-docs:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/cert-manager-offline-docs:buildcache,mode=max

  build-argo-cd-docs:
    if: >
      github.event_name == 'schedule' || 
      github.event.inputs.site_to_build == 'all' || 
      github.event.inputs.site_to_build == 'argo-cd-readthedocs-io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout official Argo CD repository
        uses: actions/checkout@v4
        with:
          repository: argoproj/argo-cd
          path: argo-cd-readthedocs-io/argo-cd-repo
          fetch-depth: 1

      - name: Prepare tags and environment
        id: prep
        run: |
          cd argo-cd-readthedocs-io/argo-cd-repo
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LC=${OWNER_LC}" >> $GITHUB_ENV

          # Detect the last 3 release branches (e.g., release-2.9 release-2.10 release-2.11)
          DETECTED_VERSIONS=$(git ls-remote --heads origin | grep -o 'refs/heads/release-[0-9]*\.[0-9]*' | sed 's|refs/heads/||' | sort -uV | tail -n 3 | tr '\n' ' ' | xargs)
          echo "OLD_VERSIONS=$DETECTED_VERSIONS" >> $GITHUB_ENV
          echo "Detected versions to build: $DETECTED_VERSIONS"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Argo CD image
        uses: docker/build-push-action@v5
        with:
          context: ./argo-cd-readthedocs-io
          file: ./argo-cd-readthedocs-io/Dockerfile
          push: true
          # Pass the dynamically detected versions to the Dockerfile
          build-args: |
            OLD_VERSIONS=${{ env.OLD_VERSIONS }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/argo-cd-offline-docs:latest
            ghcr.io/${{ env.OWNER_LC }}/argo-cd-offline-docs:${{ env.COMMIT_SHA }}
          cache-from: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/argo-cd-offline-docs:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/argo-cd-offline-docs:buildcache,mode=max

  build-fluxcd-docs:
    if: >
      github.event_name == 'schedule' || 
      github.event.inputs.site_to_build == 'all' || 
      github.event.inputs.site_to_build == 'fluxcd-io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout official FluxCD repository
        uses: actions/checkout@v4
        with:
          repository: fluxcd/website
          path: fluxcd-io/fluxcd-website
          fetch-depth: 1

      - name: Prepare tags and environment
        id: prep
        run: |
          cd fluxcd-io/fluxcd-website
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LC=${OWNER_LC}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push FluxCD image
        uses: docker/build-push-action@v5
        with:
          context: ./fluxcd-io
          file: ./fluxcd-io/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/fluxcd-offline-docs:latest
            ghcr.io/${{ env.OWNER_LC }}/fluxcd-offline-docs:${{ env.COMMIT_SHA }}
          cache-from: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/fluxcd-offline-docs:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/fluxcd-offline-docs:buildcache,mode=max

  build-ceph-docs:
    if: >
      github.event_name == 'schedule' || 
      github.event.inputs.site_to_build == 'all' || 
      github.event.inputs.site_to_build == 'docs-ceph-com'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      # Because we are building historical branches in Docker, we must disable 
      # fetch-depth: 1 here so the Docker builder has access to the full git history!
      - name: Checkout official Ceph repository
        uses: actions/checkout@v4
        with:
          repository: ceph/ceph
          path: docs-ceph-com/ceph-repo
          fetch-depth: 0

      - name: Prepare tags and environment
        id: prep
        run: |
          cd docs-ceph-com/ceph-repo
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LC=${OWNER_LC}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Ceph image
        uses: docker/build-push-action@v5
        with:
          context: ./docs-ceph-com
          file: ./docs-ceph-com/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/ceph-offline-docs:latest
            ghcr.io/${{ env.OWNER_LC }}/ceph-offline-docs:${{ env.COMMIT_SHA }}
          cache-from: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/ceph-offline-docs:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/ceph-offline-docs:buildcache,mode=max
