name: Build postgresql.org offline docs

on:
  push:
    branches: [main]
    paths:
      - 'postgresql-org/**'
      - '.github/workflows/build-postgresql-org.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout official PostgreSQL source (stable branch, shallow)
        uses: actions/checkout@v4
        with:
          repository: postgres/postgres
          ref: REL_18_STABLE
          path: postgresql-org/postgres-src
          fetch-depth: 1

      - name: Prepare tags and environment
        id: prep
        run: |
          cd postgresql-org/postgres-src
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: ./.github/actions/build-and-push-offline-docs
        with:
          image: postgresql-offline-docs
          context: ./postgresql-org
          version-tag: ${{ env.COMMIT_SHA }}
