name: Build docs.sigstore.dev offline docs

on:
  push:
    branches: [main]
    paths:
      - 'docs-sigstore-dev/**'
      - '.github/workflows/build-docs-sigstore-dev.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout official sigstore docs repository
        uses: actions/checkout@v4
        with:
          repository: sigstore/docs
          path: docs-sigstore-dev/sigstore-src
          fetch-depth: 1

      - name: Prepare tags and environment
        id: prep
        run: |
          cd docs-sigstore-dev/sigstore-src
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: ./.github/actions/build-and-push-offline-docs
        with:
          image: sigstore-offline-docs
          context: ./docs-sigstore-dev
          version-tag: ${{ env.COMMIT_SHA }}
